### ISSUE TITLE
[Git] Enhance the .gitignore

### ISSUE THREAD

**Issue by viloskovic** [experus/chaos#3]
Git is currently only ignoring the IntelliJ IDEA files.
This should be extended for maven generated folders, eclipse, ..

**Comment by vlogozzo** [comment]
NetBeans as well?

**Comment by viloskovic** [comment]
Thank you for having interest in this project, @vlogozzo! 
I am currently busy with deciding what wiill be the roadmap for the first milestone.

For this issue, I would like to support/ignore:
- [ ] Netbrains
- [ ] Eclipse
- [ ] IntelliJ IDEA (partially done)
- [ ] Maven
- [ ] Maven Release Plugin files
- [ ] OS X

After a quick search I found this: https://gist.github.com/dedunumax/54e82214715e35439227
You can enhance the current .gitignore with this file (and additional ignores if necessary) and create a pull request.

Ruben

**Comment by vlogozzo** [comment]
Do you want this on the `master` branch or the `development` branch

**Comment by viloskovic** [comment]
`development` please.
